command:
  - "python"
  - "app.py"

resources:
  - name: database
    postgres:
      branch: projects/databricks_ai_bootcamp_postgres/branches/production
      database: projects/databricks_ai_bootcamp_postgres/branches/production/databases/databricks_postgres
      permission: CAN_CONNECT_AND_CREATE
